metadata:
  name: Z80SectorZHooksSystem
  version: '0.1'
clock_hz: 1000000
reset_delay_seconds: 0
memory:
  default_size: 65536
  regions:
  - name: RAM_LOW
    start: 0
    size: 36864
    read_write: true
  - name: ROM
    start: 36864
    size: 4096
    read_only: true
  - name: RAM_HIGH
    start: 40960
    size: 24576
    read_write: true
hooks:
  pre_fetch:
    enabled: false
  post_decode:
    enabled: false
  post_execute:
    enabled: false
  port_read_pre:
    enabled: false
  port_read_post:
    enabled: false
  port_write_pre:
    enabled: false
  port_write_post:
    enabled: true
integrations:
  sectorz_demo:
    port_write_channel: stdout

components:
  ics: []
  devices: []
  hosts: []

connections: []

