"""Generate the emulator automation adapter bridge."""

from __future__ import annotations

from typing import Any, Dict


def _escape_c_string(value: object) -> str:
    return str(value).replace("\\", "\\\\").replace('"', '\\"')


def _automation_text_views(isa_data: Dict[str, Any]) -> list[dict[str, Any]]:
    automation = (isa_data.get("system", {}) or {}).get("automation", {}) or {}
    screen = automation.get("screen", {}) or {}
    views = screen.get("text_views", []) or []
    return [view for view in views if isinstance(view, dict)]


def _c_text_view_table(text_views: list[dict[str, Any]]) -> tuple[bool, str]:
    rows: list[str] = []
    for view in text_views:
        memory = view.get("memory", {}) or {}
        if str(memory.get("source", "")).strip() != "system_memory":
            continue
        layout = str(memory.get("address_layout", "linear")).strip()
        if layout not in {"linear", "bit_interleaved_rows"}:
            continue
        layout_id = "PASM_AUTOMATION_TEXT_LAYOUT_BIT_INTERLEAVED_ROWS" if layout == "bit_interleaved_rows" else "PASM_AUTOMATION_TEXT_LAYOUT_LINEAR"
        row_stride = int(view.get("row_stride", view.get("columns", 1)))
        column_multiplier = int(memory.get("column_multiplier", 1))
        rows.append(
            "    { "
            f"\"{_escape_c_string(view.get('id', 'text'))}\", "
            f"(uint32_t){int(view.get('columns', 1))}u, "
            f"(uint32_t){int(view.get('rows', 1))}u, "
            f"(uint32_t){row_stride}u, "
            f"(uint64_t){int(memory.get('base', 0))}ull, "
            f"(uint64_t){int(memory.get('alternate_base', memory.get('base', 0)))}ull, "
            f"{layout_id}, "
            f"(uint32_t){int(memory.get('row_low_mask', 0))}u, "
            f"(uint32_t){int(memory.get('row_low_shift', 0))}u, "
            f"(uint32_t){int(memory.get('row_high_shift', 0))}u, "
            f"(uint32_t){int(memory.get('row_high_multiplier', 0))}u, "
            f"(uint32_t){column_multiplier}u, "
            f"\"{_escape_c_string(view.get('charset', ''))}\", "
            f"\"{_escape_c_string(view.get('native_encoding', ''))}\", "
            f"\"{_escape_c_string(view.get('unicode_map', ''))}\" "
            "}"
        )
    if not rows:
        return False, ""
    return True, ",\n".join(rows)


def generate_automation_adapter(isa_data: Dict[str, Any], cpu_name: str) -> tuple[str, str]:
    """Generate C sources that adapt the debug ABI to the automation ABI."""

    cpu_prefix = cpu_name.lower()
    guard = f"{cpu_name.upper()}_AUTOMATION_ADAPTER_H"
    memory_default_size = int(isa_data.get("memory", {}).get("default_size", 65536))
    system_name = _escape_c_string(
        isa_data.get("system", {}).get("metadata", {}).get("name", "system")
    )
    supports_text_grid, text_view_rows = _c_text_view_table(_automation_text_views(isa_data))
    text_grid_capability = "\n        EMU_AUTOMATION_CAP_SCREEN_TEXT_GRID |" if supports_text_grid else ""
    text_grid_adapter_members = (
        f"\n    adapter.capture_text_grid = {cpu_prefix}_automation_capture_text_grid;"
        f"\n    adapter.text_grid_view_count = {cpu_prefix}_automation_text_grid_view_count;"
        f"\n    adapter.text_grid_view_descriptor = {cpu_prefix}_automation_text_grid_view_descriptor;"
        f"\n    adapter.release_text_grid = {cpu_prefix}_automation_release_text_grid;"
        if supports_text_grid
        else ""
    )
    text_grid_impl = _generate_text_grid_impl(cpu_name, cpu_prefix, text_view_rows) if supports_text_grid else ""

    header = f"""/*
 * Auto-generated automation adapter
 * Generated by PASM
 */

#ifndef {guard}
#define {guard}

#include <stddef.h>
#include "{cpu_name}_debug_abi.h"
#include "emu_automation_adapter.h"

#ifdef __cplusplus
extern "C" {{
#endif

emu_automation_result_t {cpu_prefix}_automation_attach_debug(
    CPUState *cpu,
    emu_automation_machine_t **out_machine);

emu_automation_result_t {cpu_prefix}_automation_create(
    size_t memory_size,
    emu_automation_machine_t **out_machine);

#ifdef __cplusplus
}}
#endif

#endif /* {guard} */
"""

    impl = f"""/*
 * Auto-generated automation adapter
 * Generated by PASM
 */

#include "{cpu_name}_automation_adapter.h"

#include <stdlib.h>
#include <string.h>

typedef struct {cpu_name}AutomationDebugContext {{
    CPUState *cpu;
    uint8_t owns_cpu;
}} {cpu_name}AutomationDebugContext;

static emu_automation_execution_state_t {cpu_prefix}_automation_map_mode(uint8_t mode)
{{
    switch (mode) {{
    case PASM_DBG_RUNNING: return EMU_AUTOMATION_EXECUTION_RUNNING;
    case PASM_DBG_PAUSED: return EMU_AUTOMATION_EXECUTION_PAUSED;
    case PASM_DBG_STEPPING: return EMU_AUTOMATION_EXECUTION_RUNNING;
    case PASM_DBG_EXITED: return EMU_AUTOMATION_EXECUTION_STOPPED;
    case PASM_DBG_ERROR: return EMU_AUTOMATION_EXECUTION_ERROR;
    default: return EMU_AUTOMATION_EXECUTION_ERROR;
    }}
}}

static int {cpu_prefix}_automation_core_snapshot(
    CPUState *cpu,
    PASMDebugSnapshotCore *out_core)
{{
    if (cpu == NULL || out_core == NULL) return -1;
    memset(out_core, 0, sizeof(*out_core));
    return pasm_dbg_snapshot_fill(
        cpu,
        out_core,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u,
        NULL, 0u
    );
}}

static emu_automation_result_t {cpu_prefix}_automation_describe(
    void *context,
    emu_automation_machine_descriptor_t *out_descriptor)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    PASMDebugSnapshotCore core;
    if (ctx == NULL || ctx->cpu == NULL || out_descriptor == NULL) {{
        return EMU_AUTOMATION_INVALID_ARGUMENT;
    }}
    if ({cpu_prefix}_automation_core_snapshot(ctx->cpu, &core) != 0) {{
        return EMU_AUTOMATION_ADAPTER_ERROR;
    }}
    out_descriptor->machine_id = "debug-abi";
    out_descriptor->system_id = pasm_dbg_system_name();
    out_descriptor->model_id = "{system_name}";
    out_descriptor->region = "";
    out_descriptor->video_standard = "";
    out_descriptor->adapter_version = "debug-abi-v1";
    out_descriptor->configured_memory_bytes = {memory_default_size}ull;
    out_descriptor->capabilities.feature_bits ={text_grid_capability}
        EMU_AUTOMATION_CAP_EXEC_PAUSE |
        EMU_AUTOMATION_CAP_EXEC_RESET |
        EMU_AUTOMATION_CAP_EXEC_STEP_FRAME |
        EMU_AUTOMATION_CAP_EXEC_RUN_FRAMES;
    (void)core;
    return EMU_AUTOMATION_OK;
}}

static emu_automation_result_t {cpu_prefix}_automation_capabilities(
    void *context,
    emu_automation_capabilities_t *out_capabilities)
{{
    emu_automation_machine_descriptor_t descriptor;
    memset(&descriptor, 0, sizeof(descriptor));
    descriptor.struct_size = (uint32_t)sizeof(descriptor);
    descriptor.struct_version = EMU_AUTOMATION_STRUCT_VERSION;
    descriptor.capabilities.struct_size = (uint32_t)sizeof(descriptor.capabilities);
    descriptor.capabilities.struct_version = EMU_AUTOMATION_STRUCT_VERSION;
    if ({cpu_prefix}_automation_describe(context, &descriptor) != EMU_AUTOMATION_OK) {{
        return EMU_AUTOMATION_ADAPTER_ERROR;
    }}
    out_capabilities->feature_bits = descriptor.capabilities.feature_bits;
    return EMU_AUTOMATION_OK;
}}

static emu_automation_result_t {cpu_prefix}_automation_pause(void *context)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    if (ctx == NULL || ctx->cpu == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    return pasm_dbg_pause(ctx->cpu) == 0 ? EMU_AUTOMATION_OK : EMU_AUTOMATION_ADAPTER_ERROR;
}}

static emu_automation_result_t {cpu_prefix}_automation_reset(
    void *context,
    emu_automation_reset_kind_t kind)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    if (ctx == NULL || ctx->cpu == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    if (kind != EMU_AUTOMATION_RESET_COLD && kind != EMU_AUTOMATION_RESET_WARM) {{
        return EMU_AUTOMATION_INVALID_ARGUMENT;
    }}
    pasm_dbg_reset(ctx->cpu);
    return pasm_dbg_pause(ctx->cpu) == 0 ? EMU_AUTOMATION_OK : EMU_AUTOMATION_ADAPTER_ERROR;
}}

static emu_automation_result_t {cpu_prefix}_automation_step_frame(void *context)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    PASMDebugSnapshotCore before;
    PASMDebugSnapshotCore after;
    uint64_t cycle_slice;
    uint64_t max_slices = 600u;
    uint8_t mode = PASM_DBG_ERROR;

    if (ctx == NULL || ctx->cpu == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    if ({cpu_prefix}_automation_core_snapshot(ctx->cpu, &before) != 0) {{
        return EMU_AUTOMATION_ADAPTER_ERROR;
    }}
    cycle_slice = before.system_clock_hz / 600u;
    if (cycle_slice == 0u) cycle_slice = 1024u;

    for (uint64_t i = 0u; i < max_slices; ++i) {{
        if (pasm_dbg_run_for_cycles(ctx->cpu, cycle_slice, &mode) != 0) {{
            return EMU_AUTOMATION_ADAPTER_ERROR;
        }}
        if ({cpu_prefix}_automation_core_snapshot(ctx->cpu, &after) != 0) {{
            return EMU_AUTOMATION_ADAPTER_ERROR;
        }}
        if (after.frame_index > before.frame_index) {{
            (void)pasm_dbg_pause(ctx->cpu);
            return EMU_AUTOMATION_OK;
        }}
        if (mode == PASM_DBG_EXITED || mode == PASM_DBG_ERROR) {{
            return EMU_AUTOMATION_ADAPTER_ERROR;
        }}
    }}

    (void)pasm_dbg_pause(ctx->cpu);
    return EMU_AUTOMATION_TIMEOUT;
}}

static emu_automation_result_t {cpu_prefix}_automation_run_frames(
    void *context,
    uint64_t frame_count)
{{
    for (uint64_t i = 0u; i < frame_count; ++i) {{
        emu_automation_result_t result = {cpu_prefix}_automation_step_frame(context);
        if (result != EMU_AUTOMATION_OK) return result;
    }}
    return EMU_AUTOMATION_OK;
}}

{text_grid_impl}

static void {cpu_prefix}_automation_destroy_context(void *context)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    if (ctx == NULL) return;
    if (ctx->owns_cpu != 0u && ctx->cpu != NULL) {{
        pasm_dbg_destroy(ctx->cpu);
    }}
    free(ctx);
}}

static emu_automation_result_t {cpu_prefix}_automation_attach_context(
    CPUState *cpu,
    uint8_t owns_cpu,
    emu_automation_machine_t **out_machine)
{{
    {cpu_name}AutomationDebugContext *ctx;
    emu_automation_adapter_t adapter;
    emu_automation_result_t result;

    if (cpu == NULL || out_machine == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;

    ctx = ({cpu_name}AutomationDebugContext *)calloc(1u, sizeof(*ctx));
    if (ctx == NULL) return EMU_AUTOMATION_INTERNAL_ERROR;
    ctx->cpu = cpu;
    ctx->owns_cpu = owns_cpu;

    memset(&adapter, 0, sizeof(adapter));
    adapter.struct_size = (uint32_t)sizeof(adapter);
    adapter.struct_version = EMU_AUTOMATION_STRUCT_VERSION;
    adapter.context = ctx;
    adapter.destroy_context = {cpu_prefix}_automation_destroy_context;
    adapter.describe = {cpu_prefix}_automation_describe;
    adapter.capabilities = {cpu_prefix}_automation_capabilities;
    adapter.pause = {cpu_prefix}_automation_pause;
    adapter.reset = {cpu_prefix}_automation_reset;
    adapter.step_frame = {cpu_prefix}_automation_step_frame;
    adapter.run_frames = {cpu_prefix}_automation_run_frames;
{text_grid_adapter_members}

    result = emu_automation_attach_adapter(&adapter, out_machine);
    if (result != EMU_AUTOMATION_OK) {{
        {cpu_prefix}_automation_destroy_context(ctx);
    }}
    return result;
}}

emu_automation_result_t {cpu_prefix}_automation_attach_debug(
    CPUState *cpu,
    emu_automation_machine_t **out_machine)
{{
    return {cpu_prefix}_automation_attach_context(cpu, 0u, out_machine);
}}

emu_automation_result_t {cpu_prefix}_automation_create(
    size_t memory_size,
    emu_automation_machine_t **out_machine)
{{
    CPUState *cpu;
    if (out_machine == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    if (memory_size == 0u) memory_size = {memory_default_size}u;
    cpu = pasm_dbg_create(memory_size);
    if (cpu == NULL) return EMU_AUTOMATION_INTERNAL_ERROR;
    return {cpu_prefix}_automation_attach_context(cpu, 1u, out_machine);
}}
"""

    return header, impl


def _generate_text_grid_impl(cpu_name: str, cpu_prefix: str, text_view_rows: str) -> str:
    return f"""
typedef enum {cpu_name}AutomationTextLayout {{
    PASM_AUTOMATION_TEXT_LAYOUT_LINEAR = 0,
    PASM_AUTOMATION_TEXT_LAYOUT_BIT_INTERLEAVED_ROWS = 1
}} {cpu_name}AutomationTextLayout;

typedef struct {cpu_name}AutomationTextView {{
    const char *id;
    uint32_t columns;
    uint32_t rows;
    uint32_t row_stride;
    uint64_t base;
    uint64_t alternate_base;
    {cpu_name}AutomationTextLayout layout;
    uint32_t row_low_mask;
    uint32_t row_low_shift;
    uint32_t row_high_shift;
    uint32_t row_high_multiplier;
    uint32_t column_multiplier;
    const char *charset_id;
    const char *native_encoding;
    const char *unicode_map;
}} {cpu_name}AutomationTextView;

typedef struct {cpu_name}AutomationTextGridOwned {{
    emu_automation_text_cell_t *cells;
    char *plain;
}} {cpu_name}AutomationTextGridOwned;

static const {cpu_name}AutomationTextView {cpu_prefix}_automation_text_views[] = {{
{text_view_rows}
}};

static const size_t {cpu_prefix}_automation_text_view_count =
    sizeof({cpu_prefix}_automation_text_views) / sizeof({cpu_prefix}_automation_text_views[0]);

static const {cpu_name}AutomationTextView *{cpu_prefix}_automation_find_text_view(const char *region_id)
{{
    if ({cpu_prefix}_automation_text_view_count == 0u) return NULL;
    if (region_id == NULL || region_id[0] == '\\0') {{
        return &{cpu_prefix}_automation_text_views[0];
    }}
    for (size_t i = 0u; i < {cpu_prefix}_automation_text_view_count; ++i) {{
        if (strcmp({cpu_prefix}_automation_text_views[i].id, region_id) == 0) {{
            return &{cpu_prefix}_automation_text_views[i];
        }}
    }}
    return NULL;
}}

static uint64_t {cpu_prefix}_automation_text_address(
    const {cpu_name}AutomationTextView *view,
    uint32_t row,
    uint32_t column)
{{
    uint32_t column_multiplier = (view->column_multiplier == 0u) ? 1u : view->column_multiplier;
    if (view->layout == PASM_AUTOMATION_TEXT_LAYOUT_BIT_INTERLEAVED_ROWS) {{
        return view->base +
            ((uint64_t)(row & view->row_low_mask) << view->row_low_shift) +
            ((uint64_t)(row >> view->row_high_shift) * (uint64_t)view->row_high_multiplier) +
            ((uint64_t)column * (uint64_t)column_multiplier);
    }}
    return view->base + ((uint64_t)row * (uint64_t)view->row_stride) +
        ((uint64_t)column * (uint64_t)column_multiplier);
}}

static uint32_t {cpu_prefix}_automation_apple2_codepoint(uint8_t native_code)
{{
    uint8_t ascii = (uint8_t)(native_code & 0x7Fu);
    if (ascii < 0x20u) ascii = (uint8_t)(ascii + 0x40u);
    if (ascii >= 0x20u && ascii <= 0x5Fu) return (uint32_t)ascii;
    return 0xFFFDu;
}}

static uint32_t {cpu_prefix}_automation_text_codepoint(
    const {cpu_name}AutomationTextView *view,
    uint8_t native_code)
{{
    if (view->unicode_map != NULL && strcmp(view->unicode_map, "apple2_text") == 0) {{
        return {cpu_prefix}_automation_apple2_codepoint(native_code);
    }}
    if (native_code >= 0x20u && native_code <= 0x7Eu) return (uint32_t)native_code;
    return 0xFFFDu;
}}

static uint32_t {cpu_prefix}_automation_text_attributes(
    const {cpu_name}AutomationTextView *view,
    uint8_t native_code)
{{
    if (view->unicode_map != NULL && strcmp(view->unicode_map, "apple2_text") == 0) {{
        if (native_code < 0x40u) return 1u;
        if (native_code < 0x80u) return 2u;
    }}
    return 0u;
}}

static char {cpu_prefix}_automation_plain_char(uint32_t codepoint)
{{
    if (codepoint >= 0x20u && codepoint <= 0x7Eu) return (char)codepoint;
    return '?';
}}

static emu_automation_result_t {cpu_prefix}_automation_capture_text_grid(
    void *context,
    const char *region_id,
    emu_automation_text_grid_snapshot_t *out_snapshot)
{{
    {cpu_name}AutomationDebugContext *ctx = ({cpu_name}AutomationDebugContext *)context;
    const {cpu_name}AutomationTextView *view;
    {cpu_name}AutomationTextGridOwned *owned;
    PASMDebugSnapshotCore core;
    size_t cell_count;
    size_t plain_size;
    size_t plain_index = 0u;

    if (ctx == NULL || ctx->cpu == NULL || out_snapshot == NULL) {{
        return EMU_AUTOMATION_INVALID_ARGUMENT;
    }}
    view = {cpu_prefix}_automation_find_text_view(region_id);
    if (view == NULL) return EMU_AUTOMATION_UNSUPPORTED;
    if (view->columns == 0u || view->rows == 0u) return EMU_AUTOMATION_INVALID_STATE;
    cell_count = (size_t)view->columns * (size_t)view->rows;
    plain_size = cell_count + ((view->rows > 0u) ? (size_t)(view->rows - 1u) : 0u);

    owned = ({cpu_name}AutomationTextGridOwned *)calloc(1u, sizeof(*owned));
    if (owned == NULL) return EMU_AUTOMATION_INTERNAL_ERROR;
    owned->cells = (emu_automation_text_cell_t *)calloc(cell_count, sizeof(*owned->cells));
    owned->plain = (char *)calloc(plain_size + 1u, sizeof(*owned->plain));
    if (owned->cells == NULL || owned->plain == NULL) {{
        free(owned->cells);
        free(owned->plain);
        free(owned);
        return EMU_AUTOMATION_INTERNAL_ERROR;
    }}

    if ({cpu_prefix}_automation_core_snapshot(ctx->cpu, &core) != 0) {{
        free(owned->cells);
        free(owned->plain);
        free(owned);
        return EMU_AUTOMATION_ADAPTER_ERROR;
    }}

    for (uint32_t row = 0u; row < view->rows; ++row) {{
        for (uint32_t col = 0u; col < view->columns; ++col) {{
            size_t index = ((size_t)row * (size_t)view->columns) + (size_t)col;
            uint64_t address = {cpu_prefix}_automation_text_address(view, row, col);
            uint8_t native_code = 0u;
            uint32_t codepoint;
            if (pasm_dbg_read_memory(ctx->cpu, address, &native_code, 1u) != 0) {{
                free(owned->cells);
                free(owned->plain);
                free(owned);
                return EMU_AUTOMATION_ADAPTER_ERROR;
            }}
            codepoint = {cpu_prefix}_automation_text_codepoint(view, native_code);
            owned->cells[index].struct_size = (uint32_t)sizeof(owned->cells[index]);
            owned->cells[index].struct_version = EMU_AUTOMATION_STRUCT_VERSION;
            owned->cells[index].native_code = (uint32_t)native_code;
            owned->cells[index].unicode_codepoint = codepoint;
            owned->cells[index].glyph_id = view->unicode_map;
            owned->cells[index].foreground_color = -1;
            owned->cells[index].background_color = -1;
            owned->cells[index].attribute_flags = {cpu_prefix}_automation_text_attributes(view, native_code);
            owned->cells[index].charset_id = view->charset_id;
            owned->cells[index].source_address = address;
            owned->cells[index].confidence = (codepoint == 0xFFFDu) ? 64u : 255u;
            owned->plain[plain_index++] = {cpu_prefix}_automation_plain_char(codepoint);
        }}
        if (row + 1u < view->rows) owned->plain[plain_index++] = '\\n';
    }}

    out_snapshot->frame.frame_number = core.frame_index;
    out_snapshot->frame.emulated_cycles = core.total_cycles;
    out_snapshot->frame.execution_state = {cpu_prefix}_automation_map_mode(core.mode);
    out_snapshot->region_id = view->id;
    out_snapshot->columns = view->columns;
    out_snapshot->rows = view->rows;
    out_snapshot->row_stride = view->row_stride;
    out_snapshot->cells = owned->cells;
    out_snapshot->cell_count = cell_count;
    out_snapshot->plain_utf8 = owned->plain;
    out_snapshot->plain_utf8_size = plain_index;
    out_snapshot->adapter_owned = owned;
    return EMU_AUTOMATION_OK;
}}

static emu_automation_result_t {cpu_prefix}_automation_text_grid_view_count(
    void *context,
    size_t *out_count)
{{
    (void)context;
    if (out_count == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    *out_count = {cpu_prefix}_automation_text_view_count;
    return EMU_AUTOMATION_OK;
}}

static emu_automation_result_t {cpu_prefix}_automation_text_grid_view_descriptor(
    void *context,
    size_t index,
    emu_automation_text_view_descriptor_t *out_descriptor)
{{
    const {cpu_name}AutomationTextView *view;
    (void)context;
    if (out_descriptor == NULL) return EMU_AUTOMATION_INVALID_ARGUMENT;
    if (index >= {cpu_prefix}_automation_text_view_count) return EMU_AUTOMATION_INVALID_ARGUMENT;
    view = &{cpu_prefix}_automation_text_views[index];
    out_descriptor->region_id = view->id;
    out_descriptor->columns = view->columns;
    out_descriptor->rows = view->rows;
    out_descriptor->row_stride = view->row_stride;
    out_descriptor->charset_id = view->charset_id;
    out_descriptor->native_encoding = view->native_encoding;
    out_descriptor->unicode_map = view->unicode_map;
    return EMU_AUTOMATION_OK;
}}

static void {cpu_prefix}_automation_release_text_grid(
    void *context,
    emu_automation_text_grid_snapshot_t *snapshot)
{{
    {cpu_name}AutomationTextGridOwned *owned;
    (void)context;
    if (snapshot == NULL || snapshot->adapter_owned == NULL) return;
    owned = ({cpu_name}AutomationTextGridOwned *)snapshot->adapter_owned;
    free(owned->cells);
    free(owned->plain);
    free(owned);
}}
"""
