"""Build system generator (CMake, Makefile)."""

from typing import Dict, Any, Optional

from .templates import get_template
from .cpu_hooks import HOOK_NAMES


def _hooks_enabled(isa_data: Dict[str, Any]) -> bool:
    hooks = isa_data.get("hooks", {})
    return any(hooks.get(name, {}).get("enabled", False) for name in HOOK_NAMES)


def generate_cmake(
    isa_data: Dict[str, Any],
    cpu_name: str,
    include_hooks: Optional[bool] = None,
    dispatch_mode: str = "switch",
) -> str:
    """Generate CMakeLists.txt."""

    cpu_prefix = cpu_name.lower()
    project_name = cpu_name.lower()

    has_hooks = _hooks_enabled(isa_data) if include_hooks is None else include_hooks

    extra_sources = ""
    if has_hooks:
        extra_sources += f"    src/{cpu_name}_hooks.c\n"

    dispatch_cmake = ""
    if dispatch_mode == "threaded":
        dispatch_cmake = (
            'if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")\n'
            "    add_compile_definitions(CPU_USE_THREADED_DISPATCH)\n"
            "endif()\n"
        )
    elif dispatch_mode == "both":
        dispatch_cmake = (
            'option(USE_THREADED_DISPATCH "Enable threaded dispatch (GCC/Clang)" OFF)\n'
            'if(USE_THREADED_DISPATCH AND CMAKE_C_COMPILER_ID MATCHES "GNU|Clang|AppleClang")\n'
            "    add_compile_definitions(CPU_USE_THREADED_DISPATCH)\n"
            "endif()\n"
        )
    elif dispatch_mode != "switch":
        raise ValueError(f"Unsupported dispatch mode: {dispatch_mode}")

    template = get_template("cmake")

    return template.format(
        project_name=project_name,
        cpu_name=cpu_name,
        extra_sources=extra_sources,
        dispatch_cmake=dispatch_cmake,
    )


def generate_makefile(
    isa_data: Dict[str, Any],
    cpu_name: str,
    include_hooks: Optional[bool] = None,
    dispatch_mode: str = "switch",
) -> str:
    """Generate Makefile."""

    cpu_prefix = cpu_name.lower()

    has_hooks = _hooks_enabled(isa_data) if include_hooks is None else include_hooks

    std_flag = "-std=c11"
    if dispatch_mode == "switch":
        dispatch_make = ""
    elif dispatch_mode == "threaded":
        dispatch_make = "CFLAGS += -DCPU_USE_THREADED_DISPATCH\n"
    elif dispatch_mode == "both":
        dispatch_make = (
            "DISPATCH ?= switch\n"
            "ifeq ($(DISPATCH),threaded)\n"
            "CFLAGS += -DCPU_USE_THREADED_DISPATCH\n"
            "endif\n"
        )
    else:
        raise ValueError(f"Unsupported dispatch mode: {dispatch_mode}")

    return f"""# Auto-generated Makefile
# Generated by PASM

CC = gcc
CFLAGS = -Wall -Wextra {std_flag} -O2
LDFLAGS =
{dispatch_make}

SRC_DIR = src
BUILD_DIR = build
TARGET = {cpu_prefix}_test

SOURCES = $(SRC_DIR)/main.c \\
    $(SRC_DIR)/{cpu_name}.c \\
    $(SRC_DIR)/{cpu_name}_decoder.c

# Add hooks if enabled
{f"SOURCES += $(SRC_DIR)/{cpu_name}_hooks.c" if has_hooks else ""}

OBJECTS = $(SOURCES:$(SRC_DIR)/%.c=$(BUILD_DIR)/%.o)

.PHONY: all clean run test

all: $(TARGET)

$(TARGET): $(OBJECTS)
\t$(CC) $(LDFLAGS) -o $@ $^

$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
\t@mkdir -p $(dir $@)
\t$(CC) $(CFLAGS) -c -o $@ $<

run: $(TARGET)
\t./$(TARGET)

test: $(TARGET)
\t./$(TARGET) --test basic

clean:
\trm -rf $(BUILD_DIR) $(TARGET)
"""
