"""Code templates for generated C files."""

from typing import Dict, List, Any

# License header
LICENSE_HEADER = """/*
 * Auto-generated CPU emulator
 * Generated by PASM from {isa_name} ISA definition
 * DO NOT EDIT - regenerate from ISA definition
 */

"""

# CPU header template
CPU_HEADER_TEMPLATE = (
    LICENSE_HEADER
    + """#ifndef {guard_name}_H
#define {guard_name}_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if !defined(_MSC_VER) && !defined(__clang__) && !defined(__GNUC__)
#error "Unsupported compiler: generated code supports MSVC, Clang, and GCC."
#endif

/* Include decoder for DecodedInstruction */
#include "{cpu_name}_decoder.h"

#ifdef __cplusplus
extern "C" {{
#endif

/* ===== Types ===== */
{types_code}

typedef struct CPUState CPUState;

/* ===== Hook Types ===== */
typedef enum {{
    HOOK_PRE_FETCH = 0,
    HOOK_POST_DECODE = 1,
    HOOK_POST_EXECUTE = 2,
    HOOK_PORT_READ_PRE = 3,
    HOOK_PORT_READ_POST = 4,
    HOOK_PORT_WRITE_PRE = 5,
    HOOK_PORT_WRITE_POST = 6,
    HOOK_COUNT = 7
}} HookType;

typedef struct {{
    HookType type;
    uint16_t pc;
    uint8_t prefix;
    uint8_t opcode;
    uint16_t port;
    uint8_t value;
    uint32_t raw;
}} CPUHookEvent;

typedef void (*CPUHookFunc)(CPUState *cpu, const CPUHookEvent *event, void *context);

typedef struct {{
    CPUHookFunc func;
    void *context;
    bool enabled;
}} CPUHook;

/* ===== CPU State ===== */
struct CPUState {{
{state_fields}
    
    /* Memory */
    uint8_t *memory;
    size_t memory_size;
    
    /* Port I/O */
    uint8_t *port_memory;
    size_t port_size;
    
    /* Interrupt state */
{interrupt_state_fields}
    
    /* Execution state */
    bool running;
    bool halted;
    int error_code;
    uint64_t total_cycles;
    bool pc_modified;
    uint16_t hook_pc;
    uint8_t hook_prefix;
    uint8_t hook_opcode;
    uint32_t hook_raw;
    
    /* Debug state */
    bool tracing_enabled;
    uint16_t break_points[16];
    int num_break_points;
    
    /* Hooks */
    CPUHook hooks[HOOK_COUNT];
}};

/* ===== Constants ===== */
#define CPU_ERROR_NONE 0
#define CPU_ERROR_INVALID_OPCODE 1
#define CPU_ERROR_INVALID_MEMORY 2
#define CPU_ERROR_HALT 3
{system_constants}

/* ===== Register Enum ===== */
{register_enum}

/* ===== Flag Bits ===== */
{flag_bits}

/* ===== CPU Lifecycle ===== */
CPUState *{cpu_prefix}_create(size_t memory_size);
void {cpu_prefix}_destroy(CPUState *cpu);
void {cpu_prefix}_reset(CPUState *cpu);
int {cpu_prefix}_load_rom(CPUState *cpu, const char *filename, uint16_t address);

/* ===== Execution ===== */
int {cpu_prefix}_step(CPUState *cpu);
void {cpu_prefix}_run(CPUState *cpu);
void {cpu_prefix}_run_until(CPUState *cpu, uint64_t cycles);

/* ===== Memory Access ===== */
uint8_t {cpu_prefix}_read_byte(CPUState *cpu, uint16_t addr);
void {cpu_prefix}_write_byte(CPUState *cpu, uint16_t addr, uint8_t value);
uint16_t {cpu_prefix}_read_word(CPUState *cpu, uint16_t addr);
void {cpu_prefix}_write_word(CPUState *cpu, uint16_t addr, uint16_t value);

/* ===== Port I/O ===== */
uint8_t {cpu_prefix}_read_port(CPUState *cpu, uint8_t port);
void {cpu_prefix}_write_port(CPUState *cpu, uint8_t port, uint8_t value);

/* ===== Interrupts ===== */
{interrupt_api}

/* ===== Debug ===== */
void {cpu_prefix}_dump_registers(CPUState *cpu);
void {cpu_prefix}_dump_memory(CPUState *cpu, uint16_t start, uint16_t length);
void {cpu_prefix}_dump_stack(CPUState *cpu, int depth);
void {cpu_prefix}_set_breakpoint(CPUState *cpu, uint16_t address);
void {cpu_prefix}_clear_breakpoint(CPUState *cpu, uint16_t address);
void {cpu_prefix}_list_breakpoints(CPUState *cpu);
void {cpu_prefix}_trace_enable(CPUState *cpu, bool enable);
void {cpu_prefix}_trace_instruction(CPUState *cpu, DecodedInstruction *inst);
char *{cpu_prefix}_disassemble_instruction(uint16_t pc, uint32_t raw);

#ifdef __cplusplus
}}
#endif

#endif /* {guard_name}_H */
"""
)

# CPU implementation template
CPU_IMPL_TEMPLATE = (
    LICENSE_HEADER
    + """

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "{cpu_name}.h"
#include "{cpu_name}_decoder.h"

/* ===== Private Helper Functions ===== */
{helpers_code}

/* ===== Instruction Implementation ===== */
{instructions_code}

/* ===== Dispatch ===== */
{dispatch_code}

/* ===== CPU Lifecycle ===== */
CPUState *{cpu_prefix}_create(size_t memory_size) {{
    CPUState *cpu = (CPUState *)calloc(1, sizeof(CPUState));
    if (!cpu) return NULL;
    
    cpu->memory = (uint8_t *)calloc(1, memory_size);
    if (!cpu->memory) {{
        free(cpu);
        return NULL;
    }}
    cpu->memory_size = memory_size;
    
    /* Initialize port memory */
    cpu->port_size = 256;
    cpu->port_memory = (uint8_t *)calloc(1, cpu->port_size);
    
    /* Initialize hooks */
    for (int i = 0; i < (int)HOOK_COUNT; i++) {{
        cpu->hooks[i].enabled = false;
        cpu->hooks[i].func = NULL;
        cpu->hooks[i].context = NULL;
    }}
    
    {cpu_prefix}_reset(cpu);
    return cpu;
}}

void {cpu_prefix}_destroy(CPUState *cpu) {{
    if (cpu) {{
        free(cpu->memory);
        free(cpu->port_memory);
        free(cpu);
    }}
}}

void {cpu_prefix}_reset(CPUState *cpu) {{
    memset(cpu->registers, 0, sizeof(cpu->registers));
    cpu->pc = 0;
    cpu->sp = 0;
    cpu->flags.raw = 0;
{shadow_flags_reset}
{interrupt_reset}
    cpu->running = true;
    cpu->halted = false;
    cpu->error_code = CPU_ERROR_NONE;
    cpu->total_cycles = 0;
    cpu->pc_modified = false;
    cpu->hook_pc = 0;
    cpu->hook_prefix = 0;
    cpu->hook_opcode = 0;
    cpu->hook_raw = 0;
    cpu->tracing_enabled = false;
    cpu->num_break_points = 0;
}}

int {cpu_prefix}_load_rom(CPUState *cpu, const char *filename, uint16_t address) {{
    FILE *f = fopen(filename, "rb");
    if (!f) return -1;
    
    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    
    if (address + size > cpu->memory_size) {{
        fclose(f);
        return -1;
    }}
    
    fread(&cpu->memory[address], 1, size, f);
    fclose(f);
    return 0;
}}

/* ===== Memory Access ===== */
uint8_t {cpu_prefix}_read_byte(CPUState *cpu, uint16_t addr) {{
    if (addr >= cpu->memory_size) {{
        cpu->error_code = CPU_ERROR_INVALID_MEMORY;
        return 0xFF;
    }}
    return cpu->memory[addr];
}}

void {cpu_prefix}_write_byte(CPUState *cpu, uint16_t addr, uint8_t value) {{
    if (addr >= cpu->memory_size) {{
        cpu->error_code = CPU_ERROR_INVALID_MEMORY;
        return;
    }}
{memory_write_guard}
    cpu->memory[addr] = value;
}}

uint16_t {cpu_prefix}_read_word(CPUState *cpu, uint16_t addr) {{
    uint16_t lo = {cpu_prefix}_read_byte(cpu, addr);
    uint16_t hi = {cpu_prefix}_read_byte(cpu, addr + 1);
    return lo | (hi << 8);
}}

void {cpu_prefix}_write_word(CPUState *cpu, uint16_t addr, uint16_t value) {{
    {cpu_prefix}_write_byte(cpu, addr, value & 0xFF);
    {cpu_prefix}_write_byte(cpu, addr + 1, (value >> 8) & 0xFF);
}}

/* ===== Port I/O ===== */
uint8_t {cpu_prefix}_read_port(CPUState *cpu, uint8_t port) {{
{port_read_hook_pre}
    if (port >= cpu->port_size) return 0xFF;
    uint8_t value = cpu->port_memory[port];
{port_read_hook_post}
    return value;
}}

void {cpu_prefix}_write_port(CPUState *cpu, uint8_t port, uint8_t value) {{
{port_write_hook_pre}
    if (port >= cpu->port_size) return;
    cpu->port_memory[port] = value;
{port_write_hook_post}
}}

/* ===== Interrupts ===== */
{interrupt_impl}

/* ===== Debug ===== */
void {cpu_prefix}_dump_registers(CPUState *cpu) {{
    printf("PC: 0x%04X SP: 0x%04X Flags: 0x%02X\\n", cpu->pc, cpu->sp, cpu->flags.raw);
    for (int i = 0; i < 8; i++) {{
        printf("R%d: 0x%02X ", i, cpu->registers[i]);
    }}
    printf("\\n");
}}

void {cpu_prefix}_dump_memory(CPUState *cpu, uint16_t start, uint16_t length) {{
    for (uint16_t i = 0; i < length; i++) {{
        if (i % 16 == 0) printf("\\n%04X: ", start + i);
        printf("%02X ", cpu->memory[start + i]);
    }}
    printf("\\n");
}}

void {cpu_prefix}_dump_stack(CPUState *cpu, int depth) {{
    if (depth < 0) depth = 0;
    printf("Stack from SP=0x%04X (depth=%d):\\n", cpu->sp, depth);
    for (int i = 0; i < depth; i++) {{
        uint16_t addr = (uint16_t)(cpu->sp + (uint16_t)i);
        if (addr >= cpu->memory_size) break;
        printf("  [%04X] = %02X\\n", addr, cpu->memory[addr]);
    }}
}}

void {cpu_prefix}_set_breakpoint(CPUState *cpu, uint16_t address) {{
    if (cpu->num_break_points < 16) {{
        cpu->break_points[cpu->num_break_points++] = address;
    }}
}}

void {cpu_prefix}_clear_breakpoint(CPUState *cpu, uint16_t address) {{
    for (int i = 0; i < cpu->num_break_points; i++) {{
        if (cpu->break_points[i] == address) {{
            for (int j = i; j < cpu->num_break_points - 1; j++) {{
                cpu->break_points[j] = cpu->break_points[j + 1];
            }}
            cpu->num_break_points--;
            break;
        }}
    }}
}}

void {cpu_prefix}_list_breakpoints(CPUState *cpu) {{
    printf("Breakpoints (%d):\\n", cpu->num_break_points);
    for (int i = 0; i < cpu->num_break_points; i++) {{
        printf("  %d: 0x%04X\\n", i, cpu->break_points[i]);
    }}
}}

void {cpu_prefix}_trace_enable(CPUState *cpu, bool enable) {{
    cpu->tracing_enabled = enable;
}}
{disassembler_code}

/* ===== Hook API ===== */
{hooks_impl}
"""
)

# Decoder header template
DECODER_HEADER_TEMPLATE = (
    LICENSE_HEADER
    + """#ifndef {guard_name}_DECODER_H
#define {guard_name}_DECODER_H

#include <stdint.h>
#include <stdbool.h>

/* ===== Decoded Instruction ===== */
typedef struct DecodedInstruction {{
    uint32_t raw;
    uint8_t opcode;
    uint8_t category;
    uint8_t prefix;
    uint16_t pc;
    bool valid;
    
    /* Extracted fields */
    {decoded_fields}
}} DecodedInstruction;

/* ===== Category Enum ===== */
{category_enum}

/* ===== Decode Function ===== */
DecodedInstruction {cpu_prefix}_decode(uint32_t raw, uint8_t prefix, uint16_t pc);

#endif
"""
)

# Decoder implementation template
DECODER_IMPL_TEMPLATE = (
    LICENSE_HEADER
    + """

#include "{cpu_name}_decoder.h"

/* ===== Decode Function ===== */
DecodedInstruction {cpu_prefix}_decode(uint32_t raw, uint8_t prefix, uint16_t pc) {{
    DecodedInstruction inst = {{
        .raw = raw,
        .pc = pc,
        .valid = true,
        .prefix = prefix
    }};
    
    {decode_logic}
    
    return inst;
}}
"""
)

# Hooks header template
HOOKS_HEADER_TEMPLATE = (
    LICENSE_HEADER
    + """#ifndef {guard_name}_HOOKS_H
#define {guard_name}_HOOKS_H

#include <stdint.h>
#include <stdbool.h>
#include "{cpu_name}.h"

void {cpu_prefix}_hook_set(CPUState *cpu, HookType type, CPUHookFunc func, void *context);
void {cpu_prefix}_hook_enable(CPUState *cpu, HookType type, bool enable);
void {cpu_prefix}_hook_clear(CPUState *cpu, HookType type);

#endif
"""
)

# Hooks implementation template
HOOKS_IMPL_TEMPLATE = (
    LICENSE_HEADER
    + """

#include "{cpu_name}_hooks.h"

void {cpu_prefix}_hook_set(CPUState *cpu, HookType type, CPUHookFunc func, void *context) {{
    if (type < HOOK_COUNT) {{
        cpu->hooks[type].func = func;
        cpu->hooks[type].context = context;
    }}
}}

void {cpu_prefix}_hook_enable(CPUState *cpu, HookType type, bool enable) {{
    if (type < HOOK_COUNT) {{
        cpu->hooks[type].enabled = enable;
    }}
}}

void {cpu_prefix}_hook_clear(CPUState *cpu, HookType type) {{
    if (type < HOOK_COUNT) {{
        cpu->hooks[type].func = NULL;
        cpu->hooks[type].context = NULL;
        cpu->hooks[type].enabled = false;
    }}
}}
"""
)

# CMakeLists template
CMAKE_TEMPLATE = """cmake_minimum_required(VERSION 3.16)
project({project_name}_emulator C)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_STANDARD_REQUIRED ON)

include_directories(include src)
{dispatch_cmake}

# Source files
set(SOURCES
    src/main.c
    src/{cpu_name}.c
    src/{cpu_name}_decoder.c
{extra_sources})

# Create executable
add_executable({project_name}_test ${{SOURCES}})

# Enable testing
enable_testing()
add_test(NAME basic_test COMMAND {project_name}_test --test basic)
"""

# Main.c template
MAIN_TEMPLATE = (
    LICENSE_HEADER
    + """
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "{cpu_name}.h"

void print_usage(const char *prog) {{
    printf("Usage: %s [options]\\n", prog);
    printf("Options:\\n");
    printf("  --rom <file>    Load ROM file\\n");
    printf("  --addr <addr>   Load address (default: 0x0000)\\n");
    printf("  --run           Run emulator\\n");
    printf("  --step          Run one instruction\\n");
    printf("  --cycles <n>    Run for n cycles\\n");
    printf("  --test <name>   Run test\\n");
    printf("  --help          Show this help\\n");
}}

int main(int argc, char *argv[]) {{
    CPUState *cpu = {cpu_prefix}_create(65536);
    if (!cpu) {{
        fprintf(stderr, "Failed to create CPU\\n");
        return 1;
    }}
    
    bool run_emulator = false;
    uint64_t max_cycles = 0;
    const char *rom_file = NULL;
    uint16_t load_addr = 0;
    const char *test_name = NULL;
    
    for (int i = 1; i < argc; i++) {{
        if (strcmp(argv[i], "--rom") == 0 && i + 1 < argc) {{
            rom_file = argv[++i];
        }} else if (strcmp(argv[i], "--addr") == 0 && i + 1 < argc) {{
            load_addr = (uint16_t)strtol(argv[++i], NULL, 0);
        }} else if (strcmp(argv[i], "--run") == 0) {{
            run_emulator = true;
        }} else if (strcmp(argv[i], "--cycles") == 0 && i + 1 < argc) {{
            max_cycles = strtoull(argv[++i], NULL, 0);
        }} else if (strcmp(argv[i], "--test") == 0 && i + 1 < argc) {{
            test_name = argv[++i];
        }} else if (strcmp(argv[i], "--help") == 0) {{
            print_usage(argv[0]);
            return 0;
        }}
    }}
    
    if (rom_file) {{
        if ({cpu_prefix}_load_rom(cpu, rom_file, load_addr) != 0) {{
            fprintf(stderr, "Failed to load ROM: %s\\n", rom_file);
            return 1;
        }}
        printf("Loaded ROM: %s at 0x%04X\\n", rom_file, load_addr);
    }}
    
    if (test_name) {{
        printf("Running test: %s\\n", test_name);
        if (strcmp(test_name, "basic") == 0) {{
            /* Basic test: run for a few cycles */
            {cpu_prefix}_run_until(cpu, 100);
            printf("Executed %llu cycles\\n", cpu->total_cycles);
        }}
    }} else if (run_emulator || max_cycles > 0) {{
        if (max_cycles > 0) {{
            {cpu_prefix}_run_until(cpu, max_cycles);
            printf("Executed %llu cycles\\n", cpu->total_cycles);
        }} else {{
            {cpu_prefix}_run(cpu);
        }}
    }} else {{
        print_usage(argv[0]);
    }}
    
    {cpu_prefix}_dump_registers(cpu);
    {cpu_prefix}_destroy(cpu);
    return 0;
}}
"""
)


def get_template(name: str) -> str:
    """Get a template by name."""
    templates = {
        "cpu_header": CPU_HEADER_TEMPLATE,
        "cpu_impl": CPU_IMPL_TEMPLATE,
        "decoder_header": DECODER_HEADER_TEMPLATE,
        "decoder_impl": DECODER_IMPL_TEMPLATE,
        "hooks_header": HOOKS_HEADER_TEMPLATE,
        "hooks_impl": HOOKS_IMPL_TEMPLATE,
        "cmake": CMAKE_TEMPLATE,
        "main": MAIN_TEMPLATE,
    }
    return templates.get(name, "")
