"""Generate a minimal C test harness for the generated CPU."""

from typing import Dict, Any


def generate_test_c(isa_data: Dict[str, Any], cpu_name: str) -> str:
    """Generate a very small test_cpu.c file.

    The harness just creates a CPU instance, optionally loads a ROM if the
    caller passes one, runs for a fixed number of cycles, and exits.
    """

    cpu_prefix = cpu_name.lower()

    return f"""/*
 * Auto-generated test_cpu.c
 * Generated by PASM
 */

#include <stdio.h>
#include <stdlib.h>
#include "{cpu_name}.h"

int main(int argc, char *argv[]) {{
    CPUState *cpu = {cpu_prefix}_create(65536);
    if (!cpu) {{
        fprintf(stderr, "Failed to create CPU\\n");
        return 1;
    }}

    if (argc > 1) {{
        const char *rom = argv[1];
        if ({cpu_prefix}_load_rom(cpu, rom, 0) != 0) {{
            fprintf(stderr, "Failed to load ROM: %s\\n", rom);
            {cpu_prefix}_destroy(cpu);
            return 1;
        }}
    }}

    {cpu_prefix}_run_until(cpu, 100);
    {cpu_prefix}_dump_registers(cpu);
    {cpu_prefix}_destroy(cpu);
    return 0;
}}
"""

