metadata:
  name: Apple2DefaultSystem
  version: "0.1"

clock_hz: 1023000
reset_delay_seconds: 0

memory:
  default_size: 65536
  regions:
    - name: RAM_MAIN
      start: 0x0000
      size: 0xC000
      read_write: true
    - name: ROM_SYSTEM
      start: 0xD000
      size: 0x3000
      read_only: true
  rom_images:
    - name: apple2plus_rom
      file: ../roms/apple2.rom
      target_region: ROM_SYSTEM
      offset: 0

hooks: {}
integrations:
  profile: apple2_default

components:
  ics: []
  devices: []
  hosts: []

connections: []
